# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome do Item'),
        ),
    ]
